Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.ssh.forward_x11 = true

  config.vm.network "private_network", ip: "192.168.0.10", virtualbox__intnet: "mynetwork"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = "4"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y usbip
    apt-get install -y gnome-disk-utility
  SHELL

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    echo "export DISPLAY=10.0.2.2:0" >> ~/.bash_profile
  SHELL
end
